<a href="https://colab.research.google.com/github/bindubattu/ML_23AG1A66D9/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:

list1 = [2, 4, 6, 8]


array1 = np.array(list1)

print(array1)

[2 4 6 8]


In [3]:
array1 = np.array([2, 4, 6, 8])
print(array1)

[2 4 6 8]


In [4]:
array1 = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8]])

print(array1)

[[1 2 3 4]
 [5 6 7 8]]


In [5]:
array1 = np.array([[[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]],

                [[13, 14, 15, 16],
                 [17, 18, 19, 20],
                 [21, 22, 23, 24]]])

print(array1)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [6]:
array1 = np.array([2, 4, 6])


print(array1.dtype)

int64


In [7]:
print(array1.ndim)


1


In [8]:
print(array1.size)

3


In [9]:
array1 = np.array([[1, 2, 3],
                [6, 7, 8]])


print(array1.shape)

(2, 3)


In [10]:
array1 = np.array([6, 7, 8, 10, 13])


array2 = np.array([6, 7, 8, 10, 13], dtype=np.int32)


print(array1.itemsize)
print(array2.itemsize)

8
4


In [11]:
array1 = np.array([6, 7, 8])
array2 = np.array([[1, 2, 3],
                   	    [6, 7, 8]])


print("\nData of array1 is: ",array1.data)
print("Data of array2 is: ",array2.data)


Data of array1 is:  <memory at 0x7ea916e9d840>
Data of array2 is:  <memory at 0x7ea916f1e330>


In [12]:
array1 = np.array([1, 3, 5, 7, 9])

print(array1[0])
print(array1[2])
print(array1[4])

1
5
9


In [13]:
array1[1]=10
print(array1)

[ 1 10  5  7  9]


In [14]:
array1 = np.array([[1, 3, 5, 7],
                       [9, 11, 13, 15],
                       [2, 4, 6, 8]])



element1 = array1[1, 3]
print("4th Element at 2nd Row:",element1)


element2 = array1[0, 1]
print("2nd Element at First Row:",element2)

4th Element at 2nd Row: 15
2nd Element at First Row: 3


In [15]:
array1 = np.array([1, 2, 3, 4,])
median = np.median(array1)

print(median)

2.5


In [16]:

marks = np.array([76, 78, 81, 66, 85])


mean_marks = np.mean(marks)

print(mean_marks)

77.2


In [17]:
marks = np.array([76, 78, 81, 66, 85])


std_marks = np.std(marks)
print(std_marks)

6.368673331236263


In [18]:
marks = np.array([76, 78, 81, 66, 85])


std_marks = np.percentile(marks,50)
print(std_marks)

78.0


In [19]:
marks = np.array([76, 78, 81, 66, 85])

std_marks = np.min(marks)
print(std_marks)



66


In [ ]:

marks = np.array([76, 78, 81, 66, 85])


std_marks = np.max(marks)
print(std_marks)